# Generated by Django 5.2.4 on 2025-07-11 20:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdsItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Название")),
                ("slug", models.SlugField(max_length=200, verbose_name="Slug")),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "image_url",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="items/",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("ELECTRONICS", "Электроника"),
                            ("CLOTHING", "Одежда"),
                            ("BOOKS", "Книги"),
                            ("HOME", "Для дома"),
                            ("OTHER", "Другое"),
                        ],
                        default="OTHER",
                        max_length=50,
                        verbose_name="Категория",
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("NEW", "Новый"),
                            ("LIKE_NEW", "Как новый"),
                            ("USED", "Б/у"),
                            ("DEFECT", "С дефектами"),
                        ],
                        default="USED",
                        max_length=50,
                        verbose_name="Состояние",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата последнего обновления"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ads_items",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "объявление",
                "verbose_name_plural": "объявления",
                "db_table": "app_ads",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExchangeProposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, null=True, verbose_name="Комментарий"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "ожидает"),
                            ("ACCEPTED", "принята"),
                            ("REJECTED", "отклонена"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата последнего обновления"
                    ),
                ),
                (
                    "ad_receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receive_proposals",
                        to="ads.adsitem",
                        verbose_name="Получатель",
                    ),
                ),
                (
                    "ad_sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_proposals",
                        to="ads.adsitem",
                        verbose_name="Отправитель",
                    ),
                ),
            ],
            options={
                "verbose_name": "предложение об обмене",
                "verbose_name_plural": "предложения об обмене",
                "db_table": "app_proposal",
                "ordering": ["-created_at", "-updated_at"],
            },
        ),
    ]
