# Generated by Django 5.2.4 on 2025-07-15 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_ads", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="adsitem",
            name="is_given",
            field=models.BooleanField(default=False, verbose_name="Отдан"),
        ),
    ]
