# Generated by Django 5.2.4 on 2025-07-16 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_ads", "0002_adsitem_is_given"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adsitem",
            name="image_url",
            field=models.ImageField(
                blank=True, null=True, upload_to="items/", verbose_name="Изображение"
            ),
        ),
    ]
