# Generated by Django 5.2.4 on 2025-07-13 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app_ads", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExchangeProposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, null=True, verbose_name="Комментарий"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "ожидает"),
                            ("ACCEPTED", "принята"),
                            ("REJECTED", "отклонена"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата последнего обновления"
                    ),
                ),
                (
                    "ad_receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receive_proposals",
                        to="app_ads.adsitem",
                        verbose_name="Получатель",
                    ),
                ),
                (
                    "ad_sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_proposals",
                        to="app_ads.adsitem",
                        verbose_name="Отправитель",
                    ),
                ),
            ],
            options={
                "verbose_name": "предложение об обмене",
                "verbose_name_plural": "предложения об обмене",
                "db_table": "app_proposal",
                "ordering": ["-created_at", "-updated_at"],
            },
        ),
    ]
