# Generated by Django 5.2.4 on 2025-07-15 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_proposal", "0003_alter_exchangeproposal_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="exchangeproposal",
            name="status_message",
            field=models.TextField(
                blank=True, null=True, verbose_name="Сообщение к статусу"
            ),
        ),
    ]
